version: '3'
# Manual is here: https://taskfile.dev/usage/

tasks:
  help:
    aliases: [default]
    cmd: "task --list"

  update-dependencies:
    desc: "Updates Dart dependencies"
    cmd: "fvm dart pub get"

  watch-build-runner:
    aliases: [build-runner-watch]
    cmd: "fvm dart run build_runner watch --delete-conflicting-outputs"
    desc: "Runs code generation with watch (build_runner)"

  run-build-runner:
    cmd: "fvm dart run build_runner build --delete-conflicting-outputs"
    desc: "Runs code generation (build_runner)"

  run:
    cmd: "dart lib/main.dart -D FLAVOR=prod"
    desc: "Run application"

  run-dev:
    cmd: "dart --enable-vm-service lib/main.dart"
    desc: "Run tests"

  create-module:
    cmd: "mason make serinus_module"
    desc: "Create Serinus module"
    dir: "lib"

  create-model:
    cmd: "mason make serinus_model"
    desc: "Create model object"
    dir: "lib/models"

  generate-models:
    cmd: "serinus generate models"
    desc: "Generate serinus ModelProvider"

  deploy:
    cmd: "flyctl deploy"
    desc: "Deploy service to Fly.io"

  launch:
    cmd: "flyctl launch"
    desc: "Initialize service to Fly.io"
